name: tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                go: ["1.19", "1.20", "1.21"]

        steps:
            - name: install runit
              run: |
                  sudo apt update
                  sudo apt install -y runit

            - uses: KGHactions/go-test-with-coverage@v1
              with:
                  go-version: ${{ matrix.go }}
